### PR TITLE
Preventing harded code.

### PR DESCRIPTION
**Pull request by leonascimento**
This simple pull request should avoid repeating some string many times. :)

### CODE REVIEW

**Comment by drcmda** [comment]
Small syntax error in there. Would this still work in IE, FF, SA, OP? Do they all know the webkit transform?

**Comment by leonascimento** [comment]
@taffapsn thank you very much for your review.

**Comment by TrySound** [comment]
Please run `yarn build` and commit `.size-snapshot.json` file

**Comment by leonascimento** [comment]
@TrySound @taffapsn it's done guys, thanks.

**Pull request merged**
