### PR TITLE
Refactor object exports with named exports

### PR DESCRIPTION
**Pull request by TrySound**
Refactors modules and won some bytes

### CODE REVIEW

**Comment by drcmda** [comment]
Are you planning to amend, or can be merge? Would love to have this in before i attempting to look into injects for the auto-value-fix in the react-dom target.

**Comment by TrySound** [comment]
@drcmda If you agree with everything we can merge this.

**Comment by drcmda** [comment]
Sure looks fine, only `elements` isn't needed in `Spring`.

**Comment by TrySound** [comment]
Good catch

**Pull request merged**
