### PR TITLE
Tweak unitless

### PR DESCRIPTION
**Pull request by Andarist**
followup to #191

### CODE REVIEW

**Comment by drcmda** [comment]
@Andarist could you rebase to latest? It's missing https://github.com/drcmda/react-spring/commit/533af40aa4b02c5e9504cc347b9ac4a6206c1fde

The small bit where it animates children via innerText.

**Comment by Andarist** [comment]
done

**Comment by Andarist** [comment]
This is size diff caused by this PR - https://github.com/drcmda/react-spring/compare/a449b53...91ef25c#diff-29fd455fe4a1c8d19c5e5b1420ce14faR8

I see quite a big change on master (+9kb), do u know what has caused this?

**Comment by drcmda** [comment]
Not really, the commit should've been a single line (instance.innerText(...)). 

Unless something went wrong with babel-rc, @TrySound did you notice the increase?

**Comment by Andarist** [comment]
This commit - https://github.com/drcmda/react-spring/commit/0d4d4210c4d21e3cb10176ee5f485a30729a77f6 - has introduced this regression. Investigating further...

**Comment by Andarist** [comment]
Ok, I have not reinstalled deps 🤦‍♂️  sorry for panicking 😅 everything is OK 😉

**Comment by drcmda** [comment]
😇is this ready for merging?

**Comment by Andarist** [comment]
From my POV - yeah

**Pull request merged**
