### PR TITLE
Simplify rollup

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by drcmda** [comment]
@TrySound could you recreate the size snapshot?

**Comment by TrySound** [comment]
That's 8kb more minified in umd

**Comment by TrySound** [comment]
It's okay probably. Still less than before.

**Comment by drcmda** [comment]
Oh, right - it's a habit i can't shake off, adding asyncgenerator would be terrible for bundle size. Should i change it for a promise and we rebase here or would you do it in your pR?

**Comment by TrySound** [comment]
I can rebase

**Comment by drcmda** [comment]
@TrySound  I made the update

**Comment by TrySound** [comment]
This saved only ~500B of minified code.

**Comment by drcmda** [comment]
I take it. 😄

**Pull request merged**
